### ISSUE TITLE
Simulated data

### ISSUE THREAD

**Issue by Devin-Taylor** [Smith42/heart-cnn#2]
I am looking at a similar application and would like to simulate data for the same reason as you. Would you mind sharing with me how you did this?

Thanks.

**Comment by Smith42** [comment]
Hi Devin,

As a heads up, I actually found that the analytic simulations that I
used did not work very well (and I believe that applying some classical
data augmentations would work better).

The code that I used to simulate a scan is found in the "sims" branch
under data/cone_new.py

Please let me know if you have any other questions!

Cheers,
Mike
